#include "DNDC_Interface.h"

Site_BaseInformation::Site_BaseInformation()
{
    CropModel = 0;
    Rotation_number = 0;

    for( int i = 0; i < 20; ++i )
    {
        Tillage_number[i] = 0;
        Fert_number[i] = 0;
        Flood_number[i] = 0;
        Manure_number[i] = 0;
        Irrigation_number[i] = 0;
        Grazing_number[i] = 0;
        Cut_number[i] = 0;
        plastic_film[i] = 0;
        WeedOption[i] = 0;
        m_IniWT[i] = 0.0;
        m_LWTceasingSurfFlow[i] = 0.0;
        m_LWTceasingGroungFlow[i] = 0.0;
        m_WatershedIndex[i] = 0.0;
        m_SurfOutflowIntensity[i] = 0.0;
        m_GroundOutflowIntensity[i] = 0.0;
        IrrIndex[i] = 0.0;
        FloodWaterN[i] = 0.0;
        WaterGetherIndex[i] = 0.0;
        WaterLeakRate[i] = 0.0;
        WaterControl[i] = 0;
        IrrMode[i] = 0;
        FertOption[i] = 0;

        for( int j = 0; j < 15; ++j )
        {
            TillID[i][j] = 0;
            TillMonth[i][j] = 0;
            TillDay[i][j] = 0;
            TillMethod[i][j] = 0;
            FertID[i][j] = 0;
            FertMonth[i][j] = 0;
            FertDay[i][j] = 0;
            FertMethod[i][j] = 0;
            FertNitrate[i][j] = 0.0;
            FertAbi[i][j] = 0.0;
            FertUrea[i][j] = 0.0;
            FertAnh[i][j] = 0.0;
            FertAmNi[i][j] = 0.0;
            NH42SO4[i][j] = 0.0;
            NH42HPO4[i][j] = 0.0;
            FertDepth[i][j] = 0.0;
            FertigationFile = "None0.00000";
            ManuMonth[i][j] = 0;
            ManuDay[i][j] = 0;
            ManuType[i][j] = 0;
            manu_method[i][j] = 0;
            ManuAmount[i][j] = 0.0;
            ManuCN[i][j] = 0.0; 
            ManuN[i][j] = 0.0;
            WeedMonth1[i][j] = 0;
            WeedDay1[i][j] = 0;
            WeedMonth2[i][j] = 0;
            WeedDay2[i][j] = 0;
            CoverFraction[i][j] = 0.0;
            ShallowFlood[i][j] = 0;
            FlooMonth1[i][j] = 0;
            FlooDay1[i][j] = 0;
            FlooMonth2[i][j] = 0;
            FlooDay2[i][j] = 0;
            FlooN[i][j] = 0.0;
            IrriMonth[i][j] = 0;
            IrriDay[i][j] = 0;
            IrriAmount[i][j] = 0.0;
            IrriMethod[i][j] = 0;
            GrazMonth1[i][j] = 0;
            GrazDay1[i][j] = 0;
            GrazMonth2[i][j] = 0;
            GrazDay2[i][j] = 0;
            Excreta[i][j] = 0;
            GrazHour[i][j] = 0.0;
            Dairy[i][j] = 0.0;
            Beef[i][j] = 0.0;
            Pig[i][j] = 0.0;
            Horse[i][j] = 0.0;
            Sheep[i][j] = 0.0;
            AddFeed[i][j] = 0.0;
            FeedCN[i][j] = 0.0;
            CutMonth[i][j] = 0;
            CutDay[i][j] = 0;
            CutPart[i][j] = 0;
            CutAmount[i][j] = 0.0;
            DayRelease[i][j] = 0.0;
            NIefficiency[i][j] = 0.0;
            NIduration[i][j] = 0.0;
            UreaseEfficiency[i][j] = 0.0;
            UreaseDuration[i][j] = 0.0;
        }
    }

    WT_file = "None0.00000";
    Units = 0;
    m_CN = 0.0;
    m_RoughLand = 0.0;
    m_RoughChannel = 0.0;
    m_ChannelSlope = 0.0;
    m_ChannelLength = 0.0; 
    m_LandManage = 0.0;
    latitude =0;
    longitude=120.0;
    totalday =0;
    years =0;
    ifdaily  =0;
    if1File  =0;
    Units = 0;
    db_Rotation_Number = 0;
    ClimateFileType  = 1;
    ClimateFileNumber= 0;
    NO3NH4_Rainfall  = 0;
    NH3_Atmosphere   = 0.06;
    BaseCO2= 350;
    WaterYr = 0;
    CO2IncreaseRate = 0.0;
    SOCa = 0.0;
    SOCb = 0.0;
    Soil_Texture = 0;
    Soil_Density = 0;
    Soil_pH = 0;
    Soil_OCatSurface = 0;
    Soil_Clay = 0;
    Soil_landuse = 0;
    Soil_BypassFlow  = 0;
    Soil_Litter  = 0;
    Soil_humads  = 0;
    Soil_humus   = 0;
    PassiveC = 0.0;
    Soil_NO3 = 0;// IniNO3
    Soil_NH4 = 0;// IniNH4
    Soil_moiture = 0;
    Soil_T = 0;
    SoilRetardation = 0;
    LateralInflux = 1.0;
    Soil_MicrobioIndex = 1.0;
    Soil_Quality = 0.0;
    Soil_WaterObstructLayer = 9.99;//m
    slope = 0.0;
    Fldcap = 0.0;
    Wiltpt = 0.0;
    HighestWT = 1.0;
    Soil_Porosity = 0.0;
    DClitter=1.0;
    DChumads=1.0;
    DChumus=1.0;
    HumadCN=10.0;
    HumusCN = 10.0;
    SCSuse = 0;
    Idc = 0;
    H = 0;
    Topr = 0;
    Toph = 0;
    CEC = 0;
    TH = 0;
    m = 0;
    V = 0;
    Q = 0;
    Qstar = 0;
    AcWater = 0;
    SurfWater = 0;
    SnowPack = 0;
    BypassF = 0;
    Sks = 0;
    LateralInflux= 1.0;
    Psisat= 0; 
    Beta = 0;
    MaxCrop = 0;
    MaxTill = 0;
    MaxFer = 0;
    MaxManure = 0;
    MaxWeed = 0;
    MaxFlood = 0;
    MaxIrr = 0;
    MaxGrazing = 0;
    MaxLime = 0;
    FoliageMass = 0;
    WoodMass = 0;
    LitterMass = 0;
    ForestAge = 0;
    ForestType = 0;
    SoilFertility = -1;
    SOC12 = 1;
    FolCNR = 0;
    FloorC = 0;
    LitterWater = 0;
    LitterpH = 0;
    ForestName = "";
}

Site_BaseInformation::~Site_BaseInformation()
{
    ;
}
